// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gffvzqkodzbuvghtddjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZnZ6cWtvZHpidXZnaHRkZGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDU1NDIsImV4cCI6MjA2MzU4MTU0Mn0.TtETW8fBR4j0W7LtM8k-sLaJ6C6wmVqDTbw93RN8ibU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

