name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ganti jika kamu gunakan branch lain
  workflow_dispatch: # Memungkinkan trigger manual via UI

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write # Diperlukan untuk deploy ke GitHub Pages

    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm # Cache dependencies untuk kecepatan

      - name: Install Dependencies 📦
        run: npm ci # Instal sesuai package-lock.json

      - name: Build Project 🔧
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist